#!/bin/bash
set -e

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Parse command line arguments
JAVA_VERSION=${1:-17}
CUSTOM_CPU=${2}
CUSTOM_MEMORY=${3}
CUSTOM_COUNT=${4}

echo -e "${BLUE}=== CDK Deployment Script ===${NC}"
echo ""

# Check if .env.local exists
if [ -f .env.local ]; then
  echo -e "${GREEN}Loading environment variables from .env.local${NC}"
  source .env.local
else
  echo -e "${YELLOW}Warning: .env.local not found. Attempting to get AWS info...${NC}"
  export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text 2>/dev/null || echo "")
  export AWS_REGION=${AWS_REGION:-us-east-1}
  
  if [ -z "$AWS_ACCOUNT_ID" ]; then
    echo -e "${RED}Error: Could not determine AWS account ID. Please configure AWS CLI first.${NC}"
    echo "Run: aws configure"
    exit 1
  fi
  
  export ECR_REPO="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/benchmark-app"
fi

echo "Configuration:"
echo "  Java Version: $JAVA_VERSION"
echo "  AWS Account: $AWS_ACCOUNT_ID"
echo "  AWS Region: $AWS_REGION"
echo "  ECR Repo: $ECR_REPO"

# Check if container image exists
CONTAINER_IMAGE="$ECR_REPO:java${JAVA_VERSION}"
echo "  Container Image: $CONTAINER_IMAGE"
echo ""

# Build CDK context parameters
CDK_PARAMS="-c javaVersion=${JAVA_VERSION} -c containerImage=${CONTAINER_IMAGE}"

if [ ! -z "$CUSTOM_CPU" ]; then
  CDK_PARAMS="$CDK_PARAMS -c cpu=${CUSTOM_CPU}"
  echo "  Custom CPU: ${CUSTOM_CPU}"
fi

if [ ! -z "$CUSTOM_MEMORY" ]; then
  CDK_PARAMS="$CDK_PARAMS -c memoryLimitMiB=${CUSTOM_MEMORY}"
  echo "  Custom Memory: ${CUSTOM_MEMORY} MB"
fi

if [ ! -z "$CUSTOM_COUNT" ]; then
  CDK_PARAMS="$CDK_PARAMS -c desiredCount=${CUSTOM_COUNT}"
  echo "  Custom Task Count: ${CUSTOM_COUNT}"
fi

echo ""

# Step 1: Install dependencies
echo -e "${GREEN}Step 1: Installing CDK dependencies...${NC}"
if [ ! -d "node_modules" ]; then
  npm install
else
  echo -e "${YELLOW}Dependencies already installed, skipping${NC}"
fi
echo ""

# Step 2: Bootstrap CDK (if needed)
echo -e "${GREEN}Step 2: Checking CDK bootstrap status...${NC}"
if aws cloudformation describe-stacks --stack-name CDKToolkit --region $AWS_REGION 2>/dev/null > /dev/null; then
  echo -e "${YELLOW}CDK already bootstrapped in this account/region${NC}"
else
  echo "Bootstrapping CDK..."
  cdk bootstrap aws://${AWS_ACCOUNT_ID}/${AWS_REGION}
fi
echo ""

# Step 3: Deploy the stack
echo -e "${GREEN}Step 3: Deploying infrastructure...${NC}"
echo "This may take 10-15 minutes..."
echo ""

cdk deploy $CDK_PARAMS --require-approval never

echo ""
echo -e "${GREEN}=== Deployment Complete! ===${NC}"
echo ""

# Step 4: Get and display outputs
echo -e "${GREEN}Step 4: Retrieving stack outputs...${NC}"
ALB_URL=$(aws cloudformation describe-stacks \
  --stack-name BenchmarkInfraStack \
  --region $AWS_REGION \
  --query 'Stacks[0].Outputs[?OutputKey==`AlbUrl`].OutputValue' \
  --output text)

CLUSTER_NAME=$(aws cloudformation describe-stacks \
  --stack-name BenchmarkInfraStack \
  --region $AWS_REGION \
  --query 'Stacks[0].Outputs[?OutputKey==`ClusterName`].OutputValue' \
  --output text)

DB_ENDPOINT=$(aws cloudformation describe-stacks \
  --stack-name BenchmarkInfraStack \
  --region $AWS_REGION \
  --query 'Stacks[0].Outputs[?OutputKey==`DatabaseEndpoint`].OutputValue' \
  --output text)

echo ""
echo "=== Stack Outputs ==="
echo "ALB URL: $ALB_URL"
echo "Cluster Name: $CLUSTER_NAME"
echo "Database Endpoint: $DB_ENDPOINT"
echo ""

# Save to file for easy access
cat > .env.deployment << EOF
# Auto-generated by deploy.sh
export ALB_URL=$ALB_URL
export CLUSTER_NAME=$CLUSTER_NAME
export DB_ENDPOINT=$DB_ENDPOINT
export AWS_REGION=$AWS_REGION
EOF

echo "Outputs saved to .env.deployment"
echo ""

echo -e "${YELLOW}Waiting for ECS tasks to become healthy (2-3 minutes)...${NC}"
echo "You can monitor progress with: aws logs tail /ecs/benchmark-app-java${JAVA_VERSION} --follow"
echo ""

echo -e "${GREEN}Next steps:${NC}"
echo "1. Wait 2-3 minutes for ECS tasks to start"
echo "2. Test health endpoint: curl $ALB_URL/actuator/health"
echo "3. Run verification script: ./verify-deployment.sh"
echo "4. When done, cleanup: ./destroy.sh"
