#!/bin/bash
set -e

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}=== ECR Setup and Docker Image Build Script ===${NC}"
echo ""

# Step 1: Get AWS account information
echo -e "${GREEN}Step 1: Getting AWS account information...${NC}"
export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
export AWS_REGION=${AWS_REGION:-us-east-1}

echo "AWS Account ID: $AWS_ACCOUNT_ID"
echo "AWS Region: $AWS_REGION"
echo ""

# Step 2: Create ECR repository
echo -e "${GREEN}Step 2: Creating ECR repository...${NC}"
if aws ecr describe-repositories --repository-names benchmark-app --region $AWS_REGION 2>/dev/null; then
  echo -e "${YELLOW}Repository 'benchmark-app' already exists, skipping creation${NC}"
else
  aws ecr create-repository \
    --repository-name benchmark-app \
    --region $AWS_REGION \
    --image-scanning-configuration scanOnPush=true
  echo "Repository created successfully"
fi
echo ""

# Step 3: Authenticate to ECR
echo -e "${GREEN}Step 3: Authenticating to ECR...${NC}"
aws ecr get-login-password --region $AWS_REGION | \
  docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
echo ""

# Set ECR repository URL
export ECR_REPO="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/benchmark-app"
echo "ECR Repository: $ECR_REPO"
echo ""

# Step 4: Build and push Docker images
echo -e "${GREEN}Step 4: Building and pushing Docker images...${NC}"

# Get the repository root directory (parent of cdk directory)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$REPO_ROOT/spring-boot-app"

# Determine which Java versions to build (default: all)
JAVA_VERSIONS=${JAVA_VERSIONS:-"17 21 25"}

for VERSION in $JAVA_VERSIONS; do
  echo -e "${BLUE}Building Java $VERSION image...${NC}"
  docker build -f Dockerfile.java${VERSION} -t benchmark-app:java${VERSION} .
  
  echo "Tagging image for ECR..."
  docker tag benchmark-app:java${VERSION} $ECR_REPO:java${VERSION}
  
  echo "Pushing to ECR..."
  docker push $ECR_REPO:java${VERSION}
  
  echo -e "${GREEN}✓ Java $VERSION image pushed successfully${NC}"
  echo ""
done

# Step 5: Save environment variables to file for later use
echo -e "${GREEN}Step 5: Saving environment variables...${NC}"
cat > "$REPO_ROOT/cdk/.env.local" << EOF
# Auto-generated by setup-ecr-and-images.sh
export AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
export AWS_REGION=$AWS_REGION
export ECR_REPO=$ECR_REPO
EOF

echo "Environment variables saved to cdk/.env.local"
echo ""

echo -e "${GREEN}=== Setup Complete! ===${NC}"
echo ""
echo "Next steps:"
echo "1. cd cdk"
echo "2. Source the environment: source .env.local"
echo "3. Run: ./deploy.sh <java-version>"
echo ""
echo "Example: ./deploy.sh 17"
